@CustomTemplate_CA_API_HostAddress = http://localhost:5039
@CustomTemplate_CA_API_Username = tester123

### Get User Profile
GET {{CustomTemplate_CA_API_HostAddress}}/user/{{CustomTemplate_CA_API_Username}}
Accept: application/json

###
